version: '3'
services:
#   api:
#     build:
#       context: .
#       dockerfile: api.Dockerfile
#     ports:
#       - '3000:3000'
#     container_name: farol-di-api
#     restart: always
#     volumes:
#       - api-logs:/usr/src/node-api/logs:rw
#     env_file:
#     - docker.env
    # depends_on:
    #   - db

  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: db_farol
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api-farol-di



volumes:
  api-logs:
  pg-data: