version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - '80:3000'
    container_name: api-farol-di
    restart: always
    volumes:
      - api-logs:/usr/src/node-api/logs:rw
    env_file:
    - docker.env
    networks:
      - postgres
    links:
      - postgres:postgres
    # depends_on:
    #   - pgsqlfarol

  # pgsql:
  #   image: postgres:alpine
  #   ports:
  #     - '5432:5432'
  #   container_name: 'pgsqlfarol'
  #   restart: always
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: api-farol-di

volumes:
  api-logs:
  # pg-data: